### ISSUE TITLE
google drive link for Models is not working

### ISSUE THREAD

**Issue by ertopcuburak** [kaushikjadhav01/COVID-19-Detection-Flask-App-based-on-Chest-X-rays-and-CT-Scans#19]
https://drive.google.com/file/d/1dA-rdmDmCGa3xxW5KpfLJdo7M54lPcQq/view?usp=sharing

this url is not working, so it's not possible to download models for now.

**Comment by kaushikjadhav01** [comment]
Drive link no longer needed, added models to models folder.
