### ISSUE TITLE
flask app is not working 

### ISSUE THREAD

**Issue by Mayur6999** [kaushikjadhav01/COVID-19-Detection-Flask-App-based-on-Chest-X-rays-and-CT-Scans#3]

**Comment by arpita739** [comment]
![image](https://user-images.githubusercontent.com/40695939/90866486-cb713080-e3b5-11ea-9b7d-76ce6c0753a8.png)

**Comment by khamalfa** [comment]
can you show us the error log from cmd?

**Comment by Nidhi2480** [comment]
Same error how did you solve it?
